title: 'Přidat členy inventární jednotky'
content:
  value: "<p><a href=\"/node/add/scan?edit%5Bfield_member_of%5D%5Bwidget%5D%5B0%5D%5Btarget_id%5D=[current-page:url:args:last]\">Přidat sken</a></p>\r\n"
  format: basic_html
