title: 'Přidat členy adresáře'
content:
  value: "<p><a href=\"/node/add/directory?edit%5Bfield_member_of%5D%5Bwidget%5D%5B0%5D%5Btarget_id%5D=[current-page:url:args:last]\">Přidat adresář</a></p>\r\n\r\n<p><a href=\"/node/add/inventory_item?edit%5Bfield_member_of%5D%5Bwidget%5D%5B0%5D%5Btarget_id%5D=[current-page:url:args:last]\">Přidat inventární jednotku</a></p>\r\n"
  format: basic_html
