display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      arguments:
        field_external_uri_uri:
          exception:
            title: All
  rest_export_1:
    display_options:
      arguments:
        name:
          exception:
            title: All
        vid:
          exception:
            title: All
