display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      arguments:
        vid:
          exception:
            title: All
