display:
  default:
    display_options:
      pager:
        options:
          tags:
            previous: '‹‹ Předchozí'
            next: 'Následující ››'
            first: '« První'
            last: 'Poslední »'
