display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: "{% if view is empty %}\r\n(empty)\r\n{% endif %}"
        field_group:
          label: 'Group  '
        status:
          settings:
            format_custom_false: unpublished
