display:
  default:
    display_options:
      fields:
        title:
          label: Name
        type:
          label: Type
        field_member_of:
          label: 'Member of'
      title: 'Batch edit'
