_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
abs_urls: false
admin_theme: false
roles_profiles:
  administrator:
    public: admin
    fedora: admin
  editor:
    public: editor
    fedora: editor_fedora
