_core:
  default_config_hash: X5iB4gf16luZ9La8ZO2fh0rv3JojolsVtrsHuiRI2L4
maxDepth: -1
includeSelf: false
referenceFields:
  - field_member_of
dependencies:
  module:
    - islandora
  enforced:
    module:
      - islandora_breadcrumbs
