_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b9c15bb7-e309-4b15-86e3-aec49d69b87c
name: 'Digital repository of Masaryk University Archive'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/26
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
